### ISSUE TITLE
localhost forbidden

### ISSUE THREAD

**Issue by subrama** [Georgetown-University-Libraries/AlmaInventory#2]
Hi,
I was trying to run this in the docker php version. I am getting a localhost forbidden on running it. Any suggestions? Please see screenshot attached. 

Thanks for any help.

Anna
![georgetown inventory](https://user-images.githubusercontent.com/13699942/57644919-2a2ce500-758b-11e9-90a9-613498e3cae6.PNG)

**Comment by terrywbrady** [comment]
What errors do you see in your JavaScript console?  Right click and inspect.

![image](https://user-images.githubusercontent.com/1111057/57650803-7aeb1080-7580-11e9-9118-9ad399612028.png)

**Comment by subrama** [comment]
@terrywbrady 

![georgetown error](https://user-images.githubusercontent.com/13699942/58832507-12da9800-861d-11e9-9920-6e2848bf84ab.PNG)

**Comment by terrywbrady** [comment]
The following instructions describe how to configure the Google Sheets Upload service.

https://github.com/Georgetown-University-Libraries/AlmaInventory/blob/master/README.md#pre-requisites-google-sheets

**Comment by subrama** [comment]
Hi Terry @terrywbrady 
This is before the google sheet one. This error while running the docker app.

**Comment by subrama** [comment]
![image](https://user-images.githubusercontent.com/13699942/58835082-f6d9f500-8622-11e9-93ce-1b570e656fd5.png)

It's at this section that the forbidden appears

**Comment by terrywbrady** [comment]
@subrama , If you are not ready to deploy the Google Sheet app, then please copy gsheet.prop.json.template to gsheet.prop.json.  The error is indicating that a file with that name cannot be found and parsed.

**Comment by subrama** [comment]
@terrywbrady ![image](https://user-images.githubusercontent.com/13699942/58836618-3b678f80-8627-11e9-9a35-3fb86e8fee3c.png)
It seems like it's in there

**Comment by terrywbrady** [comment]
@subrama , please 
(1)restart the docker app and 
(2)force the browser to clear your cache
(3)reload the page.
